package com.freeturn.app.ui.theme

import androidx.compose.ui.graphics.Color

// Fruit Salad palette — vibrant greens (primary), orange-red (secondary), golden yellow (tertiary)

val primaryLight = Color(0xFF3A6A00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA2F85D)
val onPrimaryContainerLight = Color(0xFF0C2000)
val secondaryLight = Color(0xFF8E4B00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC5)
val onSecondaryContainerLight = Color(0xFF2E1400)
val tertiaryLight = Color(0xFF6F5C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFE065)
val onTertiaryContainerLight = Color(0xFF221B00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8FBF0)
val onBackgroundLight = Color(0xFF181D16)
val surfaceLight = Color(0xFFF8FBF0)
val onSurfaceLight = Color(0xFF181D16)
val surfaceVariantLight = Color(0xFFDFE4D8)
val onSurfaceVariantLight = Color(0xFF43483E)
val outlineLight = Color(0xFF73786D)
val outlineVariantLight = Color(0xFFC3C8BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D322A)
val inverseOnSurfaceLight = Color(0xFFEFF2E7)
val inversePrimaryLight = Color(0xFF87D941)
val surfaceDimLight = Color(0xFFD8DBD2)
val surfaceBrightLight = Color(0xFFF8FBF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F5EA)
val surfaceContainerLight = Color(0xFFECEFE5)
val surfaceContainerHighLight = Color(0xFFE6E9DF)
val surfaceContainerHighestLight = Color(0xFFE1E4D9)



val primaryDark = Color(0xFF87D941)
val onPrimaryDark = Color(0xFF183600)
val primaryContainerDark = Color(0xFF274F00)
val onPrimaryContainerDark = Color(0xFFA2F85D)
val secondaryDark = Color(0xFFFFB87A)
val onSecondaryDark = Color(0xFF4B2500)
val secondaryContainerDark = Color(0xFF6C3400)
val onSecondaryContainerDark = Color(0xFFFFDCC5)
val tertiaryDark = Color(0xFFEAC400)
val onTertiaryDark = Color(0xFF3A2F00)
val tertiaryContainerDark = Color(0xFF544400)
val onTertiaryContainerDark = Color(0xFFFFE065)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F130E)
val onBackgroundDark = Color(0xFFE1E4D9)
val surfaceDark = Color(0xFF0F130E)
val onSurfaceDark = Color(0xFFE1E4D9)
val surfaceVariantDark = Color(0xFF43483E)
val onSurfaceVariantDark = Color(0xFFC3C8BD)
val outlineDark = Color(0xFF8D9287)
val outlineVariantDark = Color(0xFF43483E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E4D9)
val inverseOnSurfaceDark = Color(0xFF2D322A)
val inversePrimaryDark = Color(0xFF3A6A00)
val surfaceDimDark = Color(0xFF0F130E)
val surfaceBrightDark = Color(0xFF353930)
val surfaceContainerLowestDark = Color(0xFF0A0E09)
val surfaceContainerLowDark = Color(0xFF181D16)
val surfaceContainerDark = Color(0xFF1C2019)
val surfaceContainerHighDark = Color(0xFF262B23)
val surfaceContainerHighestDark = Color(0xFF31362D)
